name: portlandor
recipe: pantheon
config:
  framework: drupal8
  site: portlandor
  id: 5c6715db-abac-4633-ada8-1c9efe354629
  index: false
  edge: false
  cache: false
services:
  appserver:
    build_as_root:
      - /bin/sh -c "cp /app/cop_ca_*.crt /usr/local/share/ca-certificates/"
      - update-ca-certificates
    run_as_root:
      - /bin/sh -c "if [ ! -d /var/www/.terminus/plugins/terminus-secrets-plugin ]; then { mkdir -p /var/www/.terminus/plugins; composer create-project -d /var/www/.terminus/plugins pantheon-systems/terminus-secrets-plugin:~1; chown -R www-data:www-data /var/www/.terminus; } fi"
    xdebug: true
    config:
      conf: xdebug.ini
  node:
    type: node
    build:
      - echo "Installing Node.js dependencies..."
      - npm -C web/themes/custom/cloudy install
events:
  post-start:
    - node: echo "Building theme asset files..."
    - node: npm -C web/themes/custom/cloudy run devbuild
tooling:
  drush:
    description: Run drush commands
    service: appserver
    cmd: drush --root=/app/web
  npm:
    description: Run npm commands
    service: node
    cmd: npm -C web/themes/custom/cloudy
  node:
    description: Run node commands
    service: node
  latest:
    description: Download and import the latest database from Dev
    cmd:
      - appserver: echo "Downloading latest database..."
      - appserver: rm -f artifacts/database.tar.gz
      - appserver: terminus backup:get portlandor.dev --element=database --to=artifacts/database.tar.gz
      - appserver: echo "Importing database..."
      - database: /helpers/sql-import.sh artifacts/database.tar.gz
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
  refresh:
    description: Refresh branch by installing Composer dependencies and importing Drupal config, etc. Run after every merge from master.
    cmd:
      - appserver: echo "Installing Composer dependencies..."
      - appserver: composer install
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      - appserver: echo "Run database updates..."
      - appserver: drush updb -y
      - appserver: echo "Importing Drupal config..."
      - appserver: drush cim -y
      - appserver: echo "Clearing cache..."
      - appserver: drush cr -y
      - appserver: echo "Building theme asset files..."
      - node: npm -C web/themes/custom/cloudy run devbuild