name: portlandor
recipe: pantheon
config:
  framework: drupal8
  site: portlandor
  id: 5c6715db-abac-4633-ada8-1c9efe354629
xdebug: true
drush: composer
services:
  appserver:
    description: Add the City of Portland public certs to properly decrypt within the network
    run_as_root:
      - /bin/sh -c "cp /app/cop_ca_*.crt /usr/local/share/ca-certificates/"
      - /bin/sh -c "update-ca-certificates"
tooling:
  drush:
    service: appserver
    cmd: drush --root=/app/web
