login_path: /user/login
_core:
  default_config_hash: ZKVq7lpyGFQf-SCuj_Ng2yLPD24rKHxz-TzGQxBjLl4
paths: "~/openid-connect/azure\r\n*"
message: 'Welcome to the closed alpha version of the new website platform for Portland, Oregon. Only city employees with an Office365 account may log in at this time.'
