login_path: /user/login
_core:
  default_config_hash: ZKVq7lpyGFQf-SCuj_Ng2yLPD24rKHxz-TzGQxBjLl4
paths: "~/openid-connect/azure\r\n~/sites/default/files/**\r\n*"
message: 'Welcome to the closed alpha version of the new website platform for Portland, Oregon. Only city employees with a ROSE or PTLD account may log in at this time.'
