interval: 20000
active_on:
  content_entity_forms: true
  config_entity_forms: false
notification:
  active: true
  message: 'Saving draft...'
  delay: 1000
allowed_content_entity_types:
  node:
    bundles:
      alert: alert
      calendar_item: calendar_item
      city_charter: city_charter
      city_code: city_code
      city_service: city_service
      construction_project: construction_project
      contact: contact
      council_agenda: council_agenda
      council_document: council_document
      data_table: data_table
      development_permit: development_permit
      event: event
      external_resource: external_resource
      location: location
      news: news
      notification: notification
      page: page
      park_facility: park_facility
      policy: policy
      service_location: service_location
      top_search: top_search
_core:
  default_config_hash: QnLi3Y7e5T_v9EZqYxRb90E0bBDb2g1y7xREWLKJLC0
