report-only:
  enable: true
  directives:
    script-src:
      base: self
      flags:
        - unsafe-inline
    script-src-elem:
      base: self
    style-src:
      base: self
  reporting:
    plugin: none
enforce:
  enable: false
_core:
  default_config_hash: Qa0Wwo59NSFGS3lPsFxj55zyk3uJXxPqLJuQ4soNCaQ
