enabled: true
url: 'http://listener.logz.io:8070/?token=cksNsKvtwNECcDLmdIYgCFStyufpAajU&type=drupal'
uuid: lando-richard
severity_level: 7
_core:
  default_config_hash: 1sRItO2tXQcevdG1jbpk0lTfnhW__8zSL3vpNijZnh0
