logo:
  use_default: 0
  path: ''
_core:
  default_config_hash: 2pUFopsqxNUk-9ns4cxYr9aZWmamCbaPV0QViHChkJI
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
favicon:
  use_default: 0
  path: profiles/contrib/lightning/favicon.ico
  mimetype: image/vnd.microsoft.icon
