user_special: true
regex_pattern: '{(^group|^node|^user|^taxonomy\/term)/([0-9]+)/(.+)}'
_core:
  default_config_hash: Eee2yPxbx-GtTowlxw6bfEtn5JdpohybL_OOCy3aUEE
submit: 'Save configuration'
form_build_id: form-y3KSIDB2Tjv5C8mEBGyg3F_32g4_JsvRDDCdDF-Uytk
form_token: ZYqLCbTLHVAINfCXXUnEWDzIoTP-RKYCWYndY2Ut7l0
form_id: path_alias_xt_settings_form
op: 'Save configuration'
