user_special: true
regex_pattern: '{(^group|^node|^user|^taxonomy/term)/([0-9]+)/(.+)}'
_core:
  default_config_hash: Eee2yPxbx-GtTowlxw6bfEtn5JdpohybL_OOCy3aUEE
submit: 'Save configuration'
form_build_id: form-ESwQFVjSxeBel4eHg9oWK1O4POjjVCqi3oFxD4G0f-I
form_token: fC-9ojdoVvOsTrpUf0SeRO_6IiL_Y2uf72oECxMWqEM
form_id: path_alias_xt_settings_form
op: 'Save configuration'
