cdn_provider: ''
_core:
  default_config_hash: _5qrDuRmWmRVjW00si3U1s1NrgrocA4N653EYGRfgEE
favicon:
  mimetype: image/vnd.microsoft.icon
  path: profiles/contrib/lightning/favicon.ico
  url: 'http://portlandor.lndo.site/themes/custom/portlandor/favicon.ico'
  use_default: false
schemas:
  bootstrap: 8000
  portlandor: 8000
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: profiles/contrib/lightning/lightning.png
  url: ''
  use_default: false
navbar_inverse: 1
table: ''
