favicon:
  mimetype: image/vnd.microsoft.icon
  path: profiles/contrib/lightning/favicon.ico
  url: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: sites/default/files/City-Portland-logotype.png
  url: ''
  use_default: false
_core:
  default_config_hash: 9rAU4Pku7eMBQxauQqAgjzlcicFZ2As6zEa6zvTlCB8
